/* KONFIGURASI UJIAN — PTS BAHASA INDONESIA KELAS XII */

window.SERVER_URL = 'https://script.google.com/macros/s/AKfycbzGtY7g2qP1FB06Y4UMKpN0H74xCPk3IJrtH_IXvsBED3L-99YSp5kFY_iJ8-JRPkvz/exec';

window.DURASI_MENIT = 90;

window.MAX_VIOLATIONS = 3;